/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexcopyRouteImport } from './routes/index copy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as BooksTitleTitleTitleNameRouteImport } from './routes/books/title/title.$titleName'

const IndexcopyRoute = IndexcopyRouteImport.update({
  id: '/index copy',
  path: '/index copy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksTitleTitleTitleNameRoute =
  BooksTitleTitleTitleNameRouteImport.update({
    id: '/books/title/title/$titleName',
    path: '/books/title/title/$titleName',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/index copy': typeof IndexcopyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/title/title/$titleName': typeof BooksTitleTitleTitleNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/index copy': typeof IndexcopyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/title/title/$titleName': typeof BooksTitleTitleTitleNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/index copy': typeof IndexcopyRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/title/title/$titleName': typeof BooksTitleTitleTitleNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/index copy'
    | '/books/$bookId'
    | '/books/title/title/$titleName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/index copy'
    | '/books/$bookId'
    | '/books/title/title/$titleName'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/index copy'
    | '/books/$bookId'
    | '/books/title/title/$titleName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  IndexcopyRoute: typeof IndexcopyRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksTitleTitleTitleNameRoute: typeof BooksTitleTitleTitleNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index copy': {
      id: '/index copy'
      path: '/index copy'
      fullPath: '/index copy'
      preLoaderRoute: typeof IndexcopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/title/title/$titleName': {
      id: '/books/title/title/$titleName'
      path: '/books/title/title/$titleName'
      fullPath: '/books/title/title/$titleName'
      preLoaderRoute: typeof BooksTitleTitleTitleNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  IndexcopyRoute: IndexcopyRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  BooksTitleTitleTitleNameRoute: BooksTitleTitleTitleNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
