# Generated by Django 6.0.2 on 2026-02-20 22:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorWorksPaginationCache',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='books.author')),
                ('works_pagination', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=25)),
                ('page_number', models.IntegerField(default=1)),
                ('final_page', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='booksubject',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booksubject',
            name='subject',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='books.book'),
        ),
        migrations.AddField(
            model_name='subject',
            name='books',
            field=models.ManyToManyField(related_name='subjects', to='books.book'),
        ),
        migrations.DeleteModel(
            name='AuthorBook',
        ),
        migrations.DeleteModel(
            name='BookSubject',
        ),
    ]
