# Generated by Django 6.0.2 on 2026-02-24 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_authorworkspaginationcache_remove_booksubject_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookshelfbook',
            old_name='user_id',
            new_name='user',
        ),
    ]
