# Generated by Django 6.0.2 on 2026-02-26 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_user_id_bookshelfbook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='birth_date',
        ),
    ]
