formatted_results = {
    "numFound": 3757,
    "start": 0,
    "page": "1",
    "showin_unique": 10,
    "retrieved": "10",
    "docs": [
        {
            "title": "Harry Potter and the Philosopher's Stone",
            "open_library_key": "/works/OL82563W",
            "description": "",
            "cover_id": 15155833,
            "author_key": ["OL23919A"],
            "author_name": ["J. K. Rowling"],
        },
        {
            "title": "Harry Potter and the Deathly Hallows",
            "open_library_key": "/works/OL82586W",
            "description": "",
            "cover_id": 15158660,
            "author_key": ["OL23919A"],
            "author_name": ["J. K. Rowling"],
        },
        {
            "title": "Harry Potter and the Prisoner of Azkaban",
            "open_library_key": "/works/OL82536W",
            "description": "",
            "cover_id": 10580435,
            "author_key": ["OL23919A"],
            "author_name": ["J. K. Rowling"],
        },
        {
            "title": "Harry Potter and the Goblet of Fire",
            "open_library_key": "/works/OL82560W",
            "description": "",
            "cover_id": 12059372,
            "author_key": ["OL23919A"],
            "author_name": ["J. K. Rowling"],
        },
        {
            "title": "Harry Potter and the Order of the Phoenix",
            "open_library_key": "/works/OL82548W",
            "description": "",
            "cover_id": 15158666,
            "author_key": ["OL23919A"],
            "author_name": ["J. K. Rowling"],
        },
        {
            "title": "Harry Potter and the Half-Blood Prince",
            "open_library_key": "/works/OL82565W",
            "description": "",
            "cover_id": 10716273,
            "author_key": ["OL23919A"],
            "author_name": ["J. K. Rowling"],
        },
        {
            "title": "Harry Potter and the Chamber of Secrets",
            "open_library_key": "/works/OL82537W",
            "description": "",
            "cover_id": 15158664,
            "author_key": ["OL23919A"],
            "author_name": ["J. K. Rowling"],
        },
        {
            "title": "Harry Potter (series) 1-7",
            "open_library_key": "/works/OL14981609W",
            "description": "",
            "cover_id": 8457523,
            "author_key": ["OL23919A"],
            "author_name": ["J. K. Rowling"],
        },
        {
            "title": "Harry Potter",
            "open_library_key": "/works/OL21385222W",
            "description": "",
            "cover_id": None,
            "author_key": ["OL23919A"],
            "author_name": ["J. K. Rowling"],
        },
        {
            "title": "Harry Potter poster annual 2008",
            "open_library_key": "/works/OL20874116W",
            "description": "",
            "cover_id": 10195373,
            "author_key": ["OL7983102A"],
            "author_name": ["Warner Bros. Entertainment Inc"],
        },
    ],
}

unformatted_results = {
    'numFound': 3757,
    'start': 0,
    'numFoundExact': True,
    'num_found': 3757,
    'documentation_url': 'https://openlibrary.org/dev/docs/api/search',
    'q': 'harry potter',
    'offset': None,
    'docs': [
        {
            'author_key': ['OL23919A'],
            'author_name': ['J. K. Rowling'],
            'cover_edition_key': 'OL61027601M',
            'cover_i': 15155833,
            'ebook_access': 'borrowable',
            'edition_count': 396,
            'first_publish_year': 1997,
            'has_fulltext': True,
            'ia': [
                'harrypotterylapi0000rowl_q5r6',
                'harrypottervefel0000rowl',
                'isbn_9788204086600',
                'rbanms.24646.harrypotterphilo000jkro_e4c6',
                'bwb_W9-DHS-647',
                'harrypotter01har0000joan',
                'harrypotterochde0000unse',
                'harijspotersunfi0000unse',
                'halibote0000rowl',
                'harrypotterikami0000unse',
                'isbn_9783551317254',
                'isbn_9788000007885',
                'isbn_6780180353427',
                'isbn_9757501956008',
                'harryzzauberboxb0000jkro',
                'harrypottertome10000jkro',
                'harrypotterylapi0000unse',
                'snj.harrypotterphilo0000jkro_t6f3',
                'snj.harrypotterphilo0001jkro',
                'snj.harrypotterphilo0000jkro_s9g6',
                'harrypotterilape0000jkro',
                'haliboteyumofash0000rowl',
                'harrypotterphilo0000jkro',
                'harrypotterepedr0000jkro',
                'harrypotterogdev0000rowl',
                'harrypotterkamen0000rowl',
                'lccn_078073006991',
                'harrypotterphilo0000jkro_j6k0',
                'harrypottersorce0000unse',
                'harrypotteresbol0000rowl',
                'harrypottersorce0000rowl_a6t2',
                'harrypotterylapi0000rowl',
                'harrypotterylapi0000rowl_d7v1',
                'harrypottermagic0000rowl_p4p3',
                'harrypotteraleco0000rowl',
                'harrypottersorce0000rowl_t5a1',
                'harrypottersorce0000rowl_l6l8',
                'harrypottersorce0000rowl_i9p5',
                'harrypottersorce0000rowl_1998',
                'harrypottersorce0000rowl',
                'harrypotterylapi0000jkro',
                'harrypotterphilo0000rowl_d8d4',
                'harrypotterphilo0000rowl_i7z2',
                'harriuspotteretp0000rowl',
                'harrypotterphilo0000rowl_k0s6',
                'haliboteshenmide0000rowl',
                'hirparaauraprasa0000rowl',
                'haripattervasang0000rowl',
                'areiospoterkaihe00rowl',
                'harrypotterelapi00jkro',
                'harrypottersorce00rowl_1',
                'harrypottersorce00jkro_0',
                'harrypotterikami0000jkro',
                'harrypotterylapi00',
                'haripottatokenja00jkro',
                'harrypottersorce00rowl',
                'harrypottersorc00rowl',
                'harrypottersorce00rowl_0',
                'harrypotterphilo0000rowl_t2o9',
                'harrypotterphilo0000rowl_j1k7',
                'harrypottersorce00jkro',
                'isbn_9789984053851',
                'harrypotterylapi00rowl',
                'harrypotteraguso0000rowl',
                'garripotterifilo00jkro',
                'harrypotterundde0000jkro',
                'harrypotterdhegu0000jkro',
                'harrypotterphilo0000rowl_u9v4',
                'harispoterisiris0000jkro',
                'harripottermaeny0000jkro',
                'harrypotterlcole0000unse',
                'harrypotterochde0000unse_c9n9',
                'harrypotteriharr0000jkro',
                'harrypotterphilo0000rowl',
                'harrypottersorce0000rowl_h8m5',
                'harrypotterundde0000rowl',
                'harriuspotteretp00jkro',
                'harrypotterphilo00rowl_044',
                'harriuspotteretp00rowl',
                'bdrc-W1KG14543',
            ],
            'ia_collection': [
                'JaiGyan',
                'ServantsOfKnowledge-Print',
                'ambslibrary-ol',
                'americana',
                'americanuniversity-ol',
                'bannedbooks',
                'barryuniversity-ol',
                'belmont-ol',
                'binghamton-ol',
                'bpljordan-ol',
                'brynmawr-ol',
                'buddhist-digital-resource-center',
                'buddhist-digital-resource-center-restricted',
                'cnusd-ol',
                'cua-ol',
                'dartmouthlibrary-ol',
                'delawarecountydistrictlibrary',
                'delawarecountydistrictlibrary-ol',
                'denverpubliclibrary-ol',
                'drakeuniversity-ol',
                'goffstownlibrary-ol',
                'gwulibraries-ol',
                'hamiltonpubliclibrary-ol',
                'inlibrary',
                'internetarchivebooks',
                'ithacacollege-ol',
                'johnshopkins-ol',
                'marymount-ol',
                'miltonpubliclibrary-ol',
                'occidentalcollegelibrary-ol',
                'openlibrary-d-ol',
                'popularchinesebooks',
                'printdisabled',
                'randolph-macon-college-ol',
                'rochester-ol',
                'salisburyfreelibrary-ol',
                'spokanepubliclibrary-ol',
                'the-claremont-colleges-ol',
                'tulsacc-ol',
                'uhmauicollege-ol',
                'unb-ol',
                'uni-ol',
                'universityofarizona-ol',
                'universityofcoloradoboulder-ol',
                'universityofthewest-ol',
                'wilsoncollege-ol',
                'worthingtonlibraries-ol',
            ],
            'key': '/works/OL82563W',
            'language': [
                'jpn', 'alb', 'por', 'lav', 'dan', 'kor', 'tha', 'urd', 'gre',
                'tib', 'gla', 'nep', 'spa', 'ben', 'dut', 'grc', 'per', 'kal',
                'ara', 'rus', 'cze', 'tur', 'fin', 'cat', 'fre', 'ltz', 'swe',
                'mar', 'afr', 'lit', 'gle', 'ukr', 'ita', 'wel', 'pol', 'heb',
                'ger', 'hun', 'lat', 'hin', 'rum', 'chi', 'vie', 'eng', 'ice',
                'hrv', 'yid', 'nor', 'bul',
            ],
            'lending_edition_s': 'OL38565767M',
            'lending_identifier_s': 'harrypotterylapi0000rowl_q5r6',
            'public_scan_b': False,
            'title': "Harry Potter and the Philosopher's Stone",
        },
        {
            'author_key': ['OL23919A'],
            'author_name': ['J. K. Rowling'],
            'cover_edition_key': 'OL26378158M',
            'cover_i': 15158660,
            'ebook_access': 'printdisabled',
            'edition_count': 144,
            'first_publish_year': 2007,
            'has_fulltext': True,
            'ia': [
                'harrypotteriinsy0000unse_r7s9',
                'bwb_W8-BSR-221_t9s7',
                'harrypotter7undd0000joan',
                'harrypottereidon0000jkro',
                'garripotteridary0000jkro',
                'haliboteyusiwang0000rowl',
                'haliboteyusiwang0007rowl',
                'isbn_9780606379298',
                'bwb_P9-CCG-593',
                'isbn_9780545010221_z4n9',
                'isbn_9780545010221_i0l2',
                'isbn_9780545010221_r1m3',
                'isbn_9780545010221_x5i4',
                'harrypotter07har0000joan',
                'rbanms.24651.harrypotterdeath0000jkro_e6z9',
                'harrypottereosta0000jkro',
                'harrypotterunddi0000jkro_a5b3',
                'harrypotterdeath0000rowl_n2u6',
                'harrypotterdeath0000rowl_m2u6',
                'harrypotterdeath0000jkro_w1s3',
                'harrypotterdeath0000rowl_c0f9',
                'harrypotterdeath0000rowl_z5e5',
                'harrypotteretles0000jkro',
                'harrypotteriinsy0000jkro',
                'harrypotterylasr0000unse',
                'isbn_9780545010221',
                'harrypotterylasr00rowl',
                'harrypotteriinsy0000unse',
                'isbn_9781606868829',
                'harrypottereidon0000rowl',
                'haripoteridasikv0000rowl',
                'snj.harrypotterdeath0001unse',
                'harrypotterdeath0000rowl_a4k7',
                'isbn_9780786296651',
                'harrypotterdeath00rowl',
                'harrypotterdeath0000rowl_n2u6',
                'harrypotterdeath2009rowl',
                'garripotteridary0000rowl',
                'harrypotteretles0000rowl',
            ],
            'ia_collection': [
                'JaiGyan',
                'ServantsOfKnowledge-Print',
                'americana',
                'americanuniversity-ol',
                'bannedbooks',
                'barryuniversity-ol',
                'belmont-ol',
                'binghamton-ol',
                'bpljordan-ol',
                'cnusd-ol',
                'cua-ol',
                'dartmouthlibrary-ol',
                'delawarecountydistrictlibrary',
                'denverpubliclibrary-ol',
                'drakeuniversity-ol',
                'framingham-ol',
                'goffstownlibrary-ol',
                'gwulibraries-ol',
                'internetarchivebooks',
                'ithacacollege-ol',
                'johnshopkins-ol',
                'marygrovecollege',
                'marymount-ol',
                'occidentalcollegelibrary-ol',
                'openlibrary-d-ol',
                'popularchinesebooks',
                'printdisabled',
                'rochester-ol',
                'salisburyfreelibrary-ol',
                'spokanepubliclibrary-ol',
                'the-claremont-colleges-ol',
                'tulsacc-ol',
                'uhmauicollege-ol',
                'unb-ol',
                'uni-ol',
                'universityofarizona-ol',
                'universityofcoloradoboulder-ol',
                'universityofoklahoma-ol',
                'universityofthewest-ol',
                'wilsoncollege-ol',
                'worthingtonlibraries-ol',
            ],
            'key': '/works/OL82586W',
            'language': [
                'jpn', 'por', 'dan', 'gre', 'spa', 'ben', 'geo', 'ara', 'glg',
                'rus', 'cze', 'cat', 'fre', 'ita', 'pol', 'heb', 'est', 'ger',
                'hun', 'hin', 'chi', 'eng', 'bul',
            ],
            'public_scan_b': False,
            'title': 'Harry Potter and the Deathly Hallows',
        },
        {
            'author_key': ['OL23919A'],
            'author_name': ['J. K. Rowling'],
            'cover_edition_key': 'OL26234270M',
            'cover_i': 10580435,
            'ebook_access': 'borrowable',
            'edition_count': 278,
            'first_publish_year': 1999,
            'has_fulltext': True,
            'ia': [
                'bdrc-W8LS66814',
                'rbanms.24648.harrypotterpriso000jkro_w7j2',
                'bwb_S0-ATO-987',
                'isbn_9789994030149',
                'harrypotter03har0000joan',
                'harrypotterielpr0000unse',
                'haliboteyuazikab0000rowl',
                'isbn_9788650509739',
                'isbn_9786041008465_n2s2',
                'harrypotter0000jkro_p4k3',
                'harrypotteryelpr0000unse',
                'harrypotterveazk0000rowl',
                'snj.harrypotterpriso0000rowl_d5x1',
                'harrypotteriwiez0000jkro',
                'harrypotteriwiez0000joan',
                'harrypotterpriso0000unkn',
                'isbn_8934974048480',
                'harrypotterpriso0000rowl_n3b9',
                'harrypotterpriso0000rowl_j5w3',
                'harrypotterpriso00rowl',
                'bwb_W8-BSR-222',
                'harrypotterendeg0000rowl',
                'isbn_9781551926728',
                'isbn_9781551927329',
                'harrypotterpriso0000jkro',
                'harrypottermagic0000rowl_w0z6',
                'harrypotterpriso0000unse_k7c3',
                'haripattervazind0000rowl',
                'harrypotteretlep0000unse',
                'harrypotterpriso0000rowl_v8j4',
                'harrypotteretlep0000rowl_w4j0',
                'harrypotterdheib0000rowl',
                'harrypotterundde0000jkro_v3j2',
                'haliboteazikaban0000rowl',
                'harrypotterendeg0000jkro',
                'harrypotteryelpr0000rowl_p6x6',
                'harrypotteryelpr0000jkro',
                'harrypottersipri0000unse',
                'harrypotteryelpr0000jkro_h0c7',
                'harrypotteryelpr0003rowl',
                'harrypotteryelpr0000rowl',
                'garripotteriuzni0000rowl',
                'harrypotterpriso0000rowl_y6c2',
                'harrypotterpriso0000rowl_a8k5',
                'harrypotterpriso0000rowl_l8k3',
                'harrypotterogfan0000rowl',
                'harrypotterpriso0000rowl_y5h4',
            ],
            'ia_collection': [
                'California-State-Suggested-Reading',
                'JaiGyan',
                'ServantsOfKnowledge-Print',
                'additional_collections',
                'americana',
                'bannedbooks',
                'books',
                'buddhist-digital-resource-center',
                'buddhist-digital-resource-center-restricted',
                'inlibrary',
                'internetarchivebooks',
                'marygrovecollege',
                'popularchinesebooks',
                'printdisabled',
            ],
            'key': '/works/OL82536W',
            'language': [
                'arm', 'jpn', 'alb', 'por', 'kor', 'srp', 'urd', 'gre', 'tib',
                'spa', 'ben', 'geo', 'dut', 'ara', 'per', 'rus', 'cze', 'tur',
                'cat', 'fre', 'mar', 'swe', 'lit', 'ita', 'pol', 'heb', 'ger',
                'hun', 'nob', 'hin', 'rum', 'chi', 'vie', 'eng', 'tha', 'bul',
            ],
            'lending_edition_s': 'OL48101764M',
            'lending_identifier_s': 'bdrc-W8LS66814',
            'public_scan_b': False,
            'title': 'Harry Potter and the Prisoner of Azkaban',
        },
        {
            'author_key': ['OL23919A'],
            'author_name': ['J. K. Rowling'],
            'cover_edition_key': 'OL25683482M',
            'cover_i': 12059372,
            'ebook_access': 'printdisabled',
            'edition_count': 242,
            'first_publish_year': 2000,
            'has_fulltext': True,
            'ia': [
                'harrypotterogild0000jkro',
                'harrypotterendie0000jkro',
                'harrypotterohniv0000rowl',
                'harrypottericzar0000unse',
                'harrypottersipoc0000jkro',
                'haliboteyuhuoyan0000rowl',
                'bwb_S0-BKQ-107',
                'snj.harrypottergoble0001rowl',
                'harrypottereocal0000jkro',
                'harrypotteryelcl0000unse',
                'bwb_P8-BOL-606',
                'hocharipoterkait0000rowl',
                'rbanms.24649.harrypottergoble0000jkro_w1y9',
                'harrypottergoble0000unse_m7x4',
                'harrypottergoble0000unse_r9q3',
                'harrypottergoble0000jkro_t3n4',
                'harrypotterveate0000rowl',
                'harrypottergoble0000jkro',
                'harispoterisirug0000rowl',
                'harrypottergoble0000rowl_m3z2',
                'harrypotteretlac0000rowl_l8z4',
                'harrypottergoble0000unse',
                'harrypottergoble0000rowl_g8u7',
                'harrypottergoble00jkro',
                'harrypottergoble0000rowl_f1q1',
                'harrypotterundde00rowl',
                'harrypotteretlac0000jkro',
                'harrypottergobl00rowl',
                'harrypottergob00rowl',
                'harrypotteryelcl00jkro',
                'harrypotteretlac0000rowl',
                'isbn_9780747574507',
                'garripotterikubo00rowl',
                'harrypottergoble00rowl',
                'harrypottergoble0000rowl_o3u1',
                'harrypotteretlac0000rowl_q9p8',
                'halibotehuobeide0000rowl',
                'harrypottericzar0000unse_h2w5',
                'harrypotterendev0000unse',
                'harrypottergoble0000rowl_u7x1',
                'harrypottergoble0000rowl_q6c6',
                'harrypottergoble0000rowl',
                'bwb_C0-BHE-773',
                'harrypotteryelca0000rowl',
                'harrypottergoble0000jkro_e6v5',
                'harrypottergoble0000rowl_x6i6',
                'harrypottergoble0000rowl_k3h6',
                'harrypottergoble0000rowl_b4i1',
                'harrypottergoble0000rowl_f7d0',
                'harrypottergoble0000rowl_y3w0',
                'harrynbsppottery0004jkro',
                'harrypotteryelcl0000jkro',
                'potterharryfireo0000jkro',
                'harrypottereilca0000jkro',
                'harrypotteretlac0000rowl_p7r8',
                'snj.harrypottergoble-2.0001rowl/',
            ],
            'ia_collection': [
                'California-State-Suggested-Reading',
                'JaiGyan',
                'ServantsOfKnowledge-Print',
                'additional_collections',
                'americana',
                'bannedbooks',
                'books',
                'delawarecountydistrictlibrary',
                'internetarchivebooks',
                'marygrovecollege',
                'popularchinesebooks',
                'printdisabled',
            ],
            'key': '/works/OL82560W',
            'language': [
                'arm', 'jpn', 'alb', 'por', 'dan', 'tha', 'kor', 'urd', 'gre',
                'spa', 'ben', 'geo', 'dut', 'ara', 'rus', 'cze', 'tur', 'fre',
                'mar', 'afr', 'lit', 'swe', 'ita', 'pol', 'heb', 'ger', 'hun',
                'hin', 'rum', 'chi', 'vie', 'eng', 'nor', 'bul',
            ],
            'public_scan_b': False,
            'title': 'Harry Potter and the Goblet of Fire',
        },
        {
            'author_key': ['OL23919A'],
            'author_name': ['J. K. Rowling'],
            'cover_edition_key': 'OL25662116M',
            'cover_i': 15158666,
            'ebook_access': 'printdisabled',
            'edition_count': 246,
            'first_publish_year': 2003,
            'has_fulltext': True,
            'ia': [
                'isbn_9787020086627_z3i9',
                'harrypotteraniph0000unse',
                'harrypotterochfe0000na',
                'harrypotteriordi0000jkro',
                'harrypotterorder0000rowl_o5k6',
                'harrypotterorder0000rowl_f8o5',
                'haliboteyufenghu0005rowl',
                'haliboteyufenghu0000rowl',
                'isbn_9780329379278',
                'hairparaauramypa0000rowl',
                'harrypotterylaor0000unse_h7v4',
                'rbanms.24748.harrypotterorder0005rowl',
                'harrypotterylaor0000gemm',
                'isbn_9789645757746',
                'harrypotter5undd0000joan',
                'harrypotter05har0000joan',
                'harrypotterorder0000jkro_a2x7',
                'harrypotterorder0000jkro',
                'harrypotterogfni0000unse',
                'harrypotteresfon0000rowl',
                'harispoterisirfe0000rowl',
                'harrypotterorder0000rowl_j7r2',
                'harrypotterylaor0000jkro',
                'harrynbsppottery0000jkro',
                'harrynbsppottery0005jkro',
                'harrypotterorder0000rowl_h2t4',
                'harrypotterorder0000rowl_h7u3',
                'harrypotterorder2004rowl',
                'harrypotterorder0000rowl_g1n2',
                'harrypotterorder0000rowl_o5a3',
                'harripotteriorde0000rowl',
                'harrypotterorder00rowl',
                'harrypotterorder0000rowl_f7t9',
                'harrypotteretlor0000rowl',
                'harrypotterundde0000rowl_z3l1',
                'harptirvamafiliq0000rowl',
                'harrypotterorder00rowl_0',
                'harrypotterorde00jkro',
                'harrypotterorde00rowl',
                'harrypotterorder0000rowl_y4y8',
            ],
            'ia_collection': [
                'California-State-Suggested-Reading',
                'JaiGyan',
                'ServantsOfKnowledge-Print',
                'additional_collections',
                'americana',
                'bannedbooks',
                'books',
                'delawarecountydistrictlibrary',
                'internetarchivebooks',
                'marygrovecollege',
                'popularchinesebooks',
                'printdisabled',
                'toronto',
            ],
            'key': '/works/OL82548W',
            'language': [
                'arm', 'jpn', 'por', 'dan', 'kor', 'tha', 'spa', 'ben', 'geo',
                'dut', 'per', 'ara', 'rus', 'cze', 'tur', 'cat', 'fre', 'swe',
                'lit', 'ita', 'pol', 'heb', 'ger', 'hun', 'hin', 'rum', 'chi',
                'vie', 'eng', 'hrv', 'ukr', 'bul',
            ],
            'public_scan_b': False,
            'title': 'Harry Potter and the Order of the Phoenix',
        },
        {
            'author_key': ['OL23919A'],
            'author_name': ['J. K. Rowling'],
            'cover_i': 10716273,
            'ebook_access': 'printdisabled',
            'edition_count': 176,
            'first_publish_year': 2005,
            'has_fulltext': True,
            'ia': [
                'isbn_9789749907719',
                'rbanms.24650.harrypotterhalfb000jkro_r2k5',
                'harrypottervemel0000jkro',
                'harrypotteryelmi0000rowl',
                'isbn_9788532523105',
                'isbn_9785389077911',
                'haliboteyuhunxue0000rowl',
                'isbn_9788478889945',
                'bwb_S0-DRB-357',
                'isbn_9788183222082',
                'isbn_8934974076780',
                'harrypotteretles0000jkro_c4k4',
                'garripotteriprin0000rowl',
                'harrypotter06har0000joan',
                'harrypotter6undd0000jkro',
                'harrypotterhalfb0000rowl_u7c5',
                'harrypotterhalfb00jkro_2',
                'harrypotterhalfb0006rowl',
                'harrypotterhalfb0000rowl_a0j0',
                'harrypotterhalfb0000jkro_z6k6',
                'harrypotterhalfb0000rowl_v5f6',
                'harrypotterhalfb0000rowl_j1n7',
                'harrypottereopri0000jkro',
                'harrypotteretlep0000jkro',
                'isbn_9788372781680',
                'harrypotterhalfb0000rowl',
                'harrypotterhalfb2005rowl',
                'harrypotterhalf00rowl',
                'isbn_074758110x',
                'harrypotterhalf00rowl_0',
                'halibotehunxuewa0000rowl',
                'harrypotterhalfb0000jkro',
                'harrypotterhalfbrow00rowl',
                'harrypotterundde0000unse',
                'harrypotterhalfb0000rowl_r5b4',
                'harrypotteretlep0000rowl',
                'harrypottereoeni0000rowl',
                'harrypotteretlep0000rowl_q4e4',
                'harrypotterhalfb0000rowl_g4f8',
                'isbn_9780606348539',
                'harrypotterhalfb0000rowl_f5b2',
            ],
            'ia_collection': [
                'California-State-Suggested-Reading',
                'JaiGyan',
                'ServantsOfKnowledge-Print',
                'additional_collections',
                'americana',
                'bannedbooks',
                'books',
                'delawarecountydistrictlibrary',
                'internetarchivebooks',
                'marygrovecollege',
                'popularchinesebooks',
                'printdisabled',
            ],
            'key': '/works/OL82565W',
            'language': [
                'jpn', 'por', 'gre', 'spa', 'ben', 'ara', 'per', 'rus', 'tur',
                'fre', 'ita', 'pol', 'heb', 'ger', 'hun', 'hin', 'chi', 'vie',
                'eng', 'hrv', 'tha', 'bul',
            ],
            'public_scan_b': False,
            'title': 'Harry Potter and the Half-Blood Prince',
        },
        {
            'author_key': ['OL23919A'],
            'author_name': ['J. K. Rowling'],
            'cover_edition_key': 'OL59041259M',
            'cover_i': 15158664,
            'ebook_access': 'printdisabled',
            'edition_count': 304,
            'first_publish_year': 1998,
            'has_fulltext': True,
            'ia': [
                'snj.harrypotter0000jkro_e1f9',
                'harptirvaufrahia0000rowl',
                'harrypotterochhe0000unse',
                'harrypotterilaca0000rowl',
                'harrypotterchamb0000na',
                'harrypotteroghem0000jkro',
                'rbanms.24647.harrypotterchamb0000jkro_v5z1',
                'harrypotterchamb0000jkro_w5l2',
                'isbn_9788380082137',
                'isbn_9788498386592',
                'isbn_9780329209742',
                'isbn_9786041008465',
                'harrypotteretlac0000unse',
                'isbn_9788478885558',
                'harrypotterchamb0002rowl',
                'herrypotterchamb0000jkro',
                'harrypottertome20000jkro',
                'harrypotter02har0000joan',
                'harrypotterunddi0000jkro',
                'harrypottersicam0000jkro',
                'garripotteritana0000jkro',
                'harrypottertajem0000rowl_v2q1',
                'harrypotterchamb0000rowl_j7y0',
                'harrypotterchamb0000rowl_b8r2',
                'haliboteyumishi0000rowl',
                'harrypotterchamb0000jkro',
                'harrypotter0000unse',
                'harrypottertajem0000rowl',
                'harrypotterchamb0000rowl_i9i5',
                'harrypottermagic0000rowl',
                'harrypotterylacm0000jkro_g1c6_20thed',
                'harrypotterylacm0000jkro_t6b0',
                'harrypotterylacm0000jkro',
                'harrypotterunddi0000rowl',
                'harrypotterchamb0000rowl_f8b1',
                'isbn_9780439064866',
                'harrypotterchamb0000rowl_e1h5',
                'harrypotterchamb0000rowl_i3d9',
                'harrypotterchamb05rowl',
                'harrypotteretlac00rowl',
                'harrypotterchamb2000rowl',
                'harrypotterelaca0000unse_o3s0',
                'harrypottercham00rowl',
                'harrypotterchamb02rowl',
                'harrypotterchamb0000rowl_j9y1',
                'harrypotterchamb00rowl',
                'harrypotterchamb0000rowl_n1v0',
                'harrypotterchamb0000rowl_c5y5',
                'harrypotterchamb0000jkro_l6c0',
                'harrypotterchamb0000rowl_n8q4',
                'bdrc-W1KG14545',
            ],
            'ia_collection': [
                'JaiGyan',
                'ServantsOfKnowledge-Print',
                'ambslibrary-ol',
                'americana',
                'bannedbooks',
                'belmont-ol',
                'binghamton-ol',
                'bpljordan-ol',
                'brynmawr-ol',
                'buddhist-digital-resource-center',
                'buddhist-digital-resource-center-restricted',
                'cnusd-ol',
                'cua-ol',
                'dartmouthlibrary-ol',
                'delawarecountydistrictlibrary',
                'delawarecountydistrictlibrary-ol',
                'denverpubliclibrary-ol',
                'drakeuniversity-ol',
                'goffstownlibrary-ol',
                'hamiltonpubliclibrary-ol',
                'internetarchivebooks',
                'ithacacollege-ol',
                'johnshopkins-ol',
                'miltonpubliclibrary-ol',
                'openlibrary-d-ol',
                'printdisabled',
                'randolph-macon-college-ol',
                'rochester-ol',
                'the-claremont-colleges-ol',
                'tulsacc-ol',
                'uhmauicollege-ol',
                'unb-ol',
                'uni-ol',
                'universityofarizona-ol',
                'universityofcoloradoboulder-ol',
                'worthingtonlibraries-ol',
            ],
            'key': '/works/OL82537W',
            'language': [
                'arm', 'jpn', 'alb', 'por', 'dan', 'kor', 'tha', 'urd', 'gre',
                'tib', 'spa', 'geo', 'dut', 'per', 'ara', 'rus', 'cze', 'tur',
                'cat', 'fre', 'mar', 'swe', 'lit', 'ukr', 'ita', 'pol', 'heb',
                'ger', 'lat', 'hun', 'hin', 'rum', 'vie', 'chi', 'eng', 'fin',
                'bul',
            ],
            'public_scan_b': False,
            'title': 'Harry Potter and the Chamber of Secrets',
        },
        {
            'author_key': ['OL23919A'],
            'author_name': ['J. K. Rowling'],
            'cover_edition_key': 'OL26801911M',
            'cover_i': 8457523,
            'ebook_access': 'no_ebook',
            'edition_count': 16,
            'first_publish_year': 1999,
            'has_fulltext': False,
            'key': '/works/OL14981609W',
            'language': ['eng', 'ger'],
            'public_scan_b': False,
            'title': 'Harry Potter (series) 1-7',
        },
        {
            'author_key': ['OL23919A'],
            'author_name': ['J. K. Rowling'],
            'ebook_access': 'no_ebook',
            'edition_count': 2,
            'first_publish_year': 2001,
            'has_fulltext': False,
            'key': '/works/OL21385222W',
            'language': ['eng'],
            'public_scan_b': False,
            'title': 'Harry Potter',
        },
        {
            'author_key': ['OL7983102A'],
            'author_name': ['Warner Bros. Entertainment Inc'],
            'cover_edition_key': 'OL28267487M',
            'cover_i': 10195373,
            'ebook_access': 'borrowable',
            'edition_count': 1,
            'first_publish_year': 2007,
            'has_fulltext': True,
            'ia': ['harrypotterposte0000unse'],
            'ia_collection': ['inlibrary', 'internetarchivebooks', 'printdisabled'],
            'key': '/works/OL20874116W',
            'language': ['eng'],
            'lending_edition_s': 'OL28267487M',
            'lending_identifier_s': 'harrypotterposte0000unse',
            'public_scan_b': False,
            'title': 'Harry Potter poster annual 2008',
        },
    ],
}
